
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/YOURUSER/YOURREPO.git'
    targetRevision: HEAD
    path: helm-charts/mlops
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mlops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
