{{- range .Values.namespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  labels:
    {{- range $key, $value := .labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
  annotations:
    meta.helm.sh/release-name: {{ $.Release.Name }}
    meta.helm.sh/release-namespace: {{ $.Release.Namespace }}
spec: {}
{{- end }}

---
# Network Policy for DMZ Architecture
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: iip-dmz-policy
  namespace: iip-infrastructure
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          tier: applications
    - namespaceSelector:
        matchLabels:
          tier: monitoring
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          tier: applications
  - to:
    - namespaceSelector:
        matchLabels:
          tier: mlops
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: iip-applications-policy
  namespace: iip-applications
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          tier: infrastructure
    - podSelector:
        matchLabels:
          app: kong
  - from: []
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          tier: infrastructure
  - to:
    - namespaceSelector:
        matchLabels:
          tier: mlops
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 443

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: iip-mlops-policy
  namespace: iip-mlops
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          tier: applications
    - namespaceSelector:
        matchLabels:
          tier: infrastructure
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          tier: infrastructure
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 443